name: Spider
main: be.bhasher.spider.Spider
version: ${project.version}
api-version: 1.13

author: Bhasher

commands:
  walkspeed:
    description: Change the player's walkspeed to test the antispeedhack.
    usage: "§cSyntax error! §f/walkspeed [player] <new walkspeed>"
    permission: spider.command.walkspeed
    aliases:
      - ws

  prevent:
    description: Warn a player.
    usage: "§cSyntax error! §ftype /prevent help for more information."
    permission: spider.command.prevent
    aliases:
      - pv